// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizGame.Infrastructure.Persistence;

#nullable disable

namespace QuizGame.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QuizGameDbContext))]
    [Migration("20260909103808_AddResilienceColumns")]
    partial class AddResilienceColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizGame.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int")
                        .HasColumnName("DifficultyLevel");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrizeAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrizeAmount");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("59ef08e6-1514-4379-87a1-c1b802d616ba"),
                            Description = "Foundational programming and tooling questions.",
                            DifficultyLevel = 1,
                            IsActive = true,
                            Name = "Software Development",
                            PrizeAmount = 100m
                        },
                        new
                        {
                            Id = new Guid("36cafaf0-b7cd-4556-9ac7-4b5b83f39118"),
                            Description = "Architectural styles, design patterns and system design questions.",
                            DifficultyLevel = 2,
                            IsActive = true,
                            Name = "Software Architecture",
                            PrizeAmount = 500m
                        },
                        new
                        {
                            Id = new Guid("1ab48485-17e9-4eae-bcf6-113bbf0135c6"),
                            Description = "Advanced data pipelines and machine learning questions for the final rounds.",
                            DifficultyLevel = 3,
                            IsActive = true,
                            Name = "Data & AI Engineering",
                            PrizeAmount = 2000m
                        });
                });

            modelBuilder.Entity("QuizGame.Domain.Games.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AccumulatedPrize")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AccumulatedPrize");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("int")
                        .HasColumnName("CurrentRound");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("PlayerName");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.ToTable("Games", "dbo");
                });

            modelBuilder.Entity("QuizGame.Domain.Games.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AnsweredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CorrectAnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DeadlineUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int")
                        .HasColumnName("Number");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Outcome");

                    b.Property<decimal>("PrizeAtStake")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrizeAtStake");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SelectedAnswerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Number")
                        .IsUnique();

                    b.ToTable("Rounds", "dbo");
                });

            modelBuilder.Entity("QuizGame.Domain.Questions.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a740a2b-f51a-4927-bc7a-e4e65d875225"),
                            IsCorrect = false,
                            QuestionId = new Guid("bca1ad0d-c8e0-48f7-a83e-39d71540c206"),
                            Text = "Aplicación de Procesos Internos"
                        },
                        new
                        {
                            Id = new Guid("8faea26f-c49a-4353-b580-36eaa695f69b"),
                            IsCorrect = true,
                            QuestionId = new Guid("bca1ad0d-c8e0-48f7-a83e-39d71540c206"),
                            Text = "Interfaz de Programación de Aplicaciones"
                        },
                        new
                        {
                            Id = new Guid("d4db326d-da94-4123-bfde-1b73c44d51a5"),
                            IsCorrect = false,
                            QuestionId = new Guid("bca1ad0d-c8e0-48f7-a83e-39d71540c206"),
                            Text = "Arquitectura de Programas Integrados"
                        },
                        new
                        {
                            Id = new Guid("e41bfa0b-4c9d-4698-bb4e-4f69a4ef3d3b"),
                            IsCorrect = false,
                            QuestionId = new Guid("bca1ad0d-c8e0-48f7-a83e-39d71540c206"),
                            Text = "Análisis de Producto Informático"
                        },
                        new
                        {
                            Id = new Guid("b76cd511-1cbc-4ccb-9745-83f1dca17d88"),
                            IsCorrect = false,
                            QuestionId = new Guid("2a32cdc7-1c3a-4d84-b9e0-06ce7fca26ac"),
                            Text = "Docker"
                        },
                        new
                        {
                            Id = new Guid("6ede8f53-90d2-4bf2-a12b-fa23aeb867b0"),
                            IsCorrect = false,
                            QuestionId = new Guid("2a32cdc7-1c3a-4d84-b9e0-06ce7fca26ac"),
                            Text = "Nginx"
                        },
                        new
                        {
                            Id = new Guid("6df053aa-fd38-4a71-afd0-28a320ac566a"),
                            IsCorrect = true,
                            QuestionId = new Guid("2a32cdc7-1c3a-4d84-b9e0-06ce7fca26ac"),
                            Text = "Git"
                        },
                        new
                        {
                            Id = new Guid("c8b6dc4e-4ec2-4c07-9e40-097c01176227"),
                            IsCorrect = false,
                            QuestionId = new Guid("2a32cdc7-1c3a-4d84-b9e0-06ce7fca26ac"),
                            Text = "Redis"
                        },
                        new
                        {
                            Id = new Guid("32a71eb0-394b-4411-b995-bb8204edf856"),
                            IsCorrect = true,
                            QuestionId = new Guid("095aa9ae-8d60-46a1-bba6-78e9fa6c86e7"),
                            Text = "Cola"
                        },
                        new
                        {
                            Id = new Guid("0c62b880-f2b6-49c3-ae54-549aed98786e"),
                            IsCorrect = false,
                            QuestionId = new Guid("095aa9ae-8d60-46a1-bba6-78e9fa6c86e7"),
                            Text = "Pila"
                        },
                        new
                        {
                            Id = new Guid("14b94f04-b857-46e3-bc6f-8f37b237f363"),
                            IsCorrect = false,
                            QuestionId = new Guid("095aa9ae-8d60-46a1-bba6-78e9fa6c86e7"),
                            Text = "Árbol"
                        },
                        new
                        {
                            Id = new Guid("8fc0d028-64ba-48d8-8c57-b4a3b209ef91"),
                            IsCorrect = false,
                            QuestionId = new Guid("095aa9ae-8d60-46a1-bba6-78e9fa6c86e7"),
                            Text = "Grafo"
                        },
                        new
                        {
                            Id = new Guid("6c409052-d21b-4c9b-90a5-e85c76fda3eb"),
                            IsCorrect = false,
                            QuestionId = new Guid("7992d28c-4399-4180-a957-8755f76e1184"),
                            Text = "HTML"
                        },
                        new
                        {
                            Id = new Guid("7bec1930-def7-47ac-84b1-11de96b87c87"),
                            IsCorrect = true,
                            QuestionId = new Guid("7992d28c-4399-4180-a957-8755f76e1184"),
                            Text = "CSS"
                        },
                        new
                        {
                            Id = new Guid("b3ab0076-11ea-4df7-b14f-ebb685adad09"),
                            IsCorrect = false,
                            QuestionId = new Guid("7992d28c-4399-4180-a957-8755f76e1184"),
                            Text = "SQL"
                        },
                        new
                        {
                            Id = new Guid("dc198a2a-0e14-4605-8540-f0cac3724a13"),
                            IsCorrect = false,
                            QuestionId = new Guid("7992d28c-4399-4180-a957-8755f76e1184"),
                            Text = "JSON"
                        },
                        new
                        {
                            Id = new Guid("0709943d-63f7-4d98-b4e7-89a62c8c690c"),
                            IsCorrect = false,
                            QuestionId = new Guid("427c79c8-d4b8-48c4-9308-b7eb1ddf140e"),
                            Text = "Sistema de Consultas Lineales"
                        },
                        new
                        {
                            Id = new Guid("d949a619-63f4-4487-879d-2bccc39118b3"),
                            IsCorrect = false,
                            QuestionId = new Guid("427c79c8-d4b8-48c4-9308-b7eb1ddf140e"),
                            Text = "Software de Control Lógico"
                        },
                        new
                        {
                            Id = new Guid("c28194f2-bf5e-408a-83f3-ae4abf295e2b"),
                            IsCorrect = true,
                            QuestionId = new Guid("427c79c8-d4b8-48c4-9308-b7eb1ddf140e"),
                            Text = "Lenguaje de Consulta Estructurado"
                        },
                        new
                        {
                            Id = new Guid("b209bea0-cc42-44cb-9643-ab885a46c6fa"),
                            IsCorrect = false,
                            QuestionId = new Guid("427c79c8-d4b8-48c4-9308-b7eb1ddf140e"),
                            Text = "Simulación de Cadenas Lineales"
                        },
                        new
                        {
                            Id = new Guid("46f12667-a4bd-4183-bd36-d24c7c84e068"),
                            IsCorrect = false,
                            QuestionId = new Guid("a4999ba8-15f3-4585-844a-0f0e1f17dcee"),
                            Text = "Arreglo"
                        },
                        new
                        {
                            Id = new Guid("58155e79-65f0-4ecb-9f0c-bc278f2169a3"),
                            IsCorrect = false,
                            QuestionId = new Guid("a4999ba8-15f3-4585-844a-0f0e1f17dcee"),
                            Text = "Objeto"
                        },
                        new
                        {
                            Id = new Guid("5b97921c-55f9-49f4-80cf-32240dffb935"),
                            IsCorrect = false,
                            QuestionId = new Guid("a4999ba8-15f3-4585-844a-0f0e1f17dcee"),
                            Text = "Clase"
                        },
                        new
                        {
                            Id = new Guid("5d13aff7-6d70-4707-a825-408ccc728844"),
                            IsCorrect = true,
                            QuestionId = new Guid("a4999ba8-15f3-4585-844a-0f0e1f17dcee"),
                            Text = "Booleano"
                        },
                        new
                        {
                            Id = new Guid("cfcec57d-dfb5-40a9-8be9-be3b0066fa05"),
                            IsCorrect = false,
                            QuestionId = new Guid("3fa633a4-6979-45a9-a589-cf8c2754b6ec"),
                            Text = "CRUD"
                        },
                        new
                        {
                            Id = new Guid("357fd4f3-28a7-42d9-8ed3-9eeea8b3651f"),
                            IsCorrect = true,
                            QuestionId = new Guid("3fa633a4-6979-45a9-a589-cf8c2754b6ec"),
                            Text = "MVC"
                        },
                        new
                        {
                            Id = new Guid("26f60334-ec80-444b-9099-514204cdac89"),
                            IsCorrect = false,
                            QuestionId = new Guid("3fa633a4-6979-45a9-a589-cf8c2754b6ec"),
                            Text = "REST"
                        },
                        new
                        {
                            Id = new Guid("1cb66463-8ecd-403f-af9b-9df36c213021"),
                            IsCorrect = false,
                            QuestionId = new Guid("3fa633a4-6979-45a9-a589-cf8c2754b6ec"),
                            Text = "SOAP"
                        },
                        new
                        {
                            Id = new Guid("8500a296-cb9e-4e97-8c5c-b2f2d96ec446"),
                            IsCorrect = false,
                            QuestionId = new Guid("3c933504-e478-4984-9044-365bd27ccb6c"),
                            Text = "Un solo proceso monolítico"
                        },
                        new
                        {
                            Id = new Guid("e3f1ab62-6c00-4aa1-ba53-7ad08e2c09c8"),
                            IsCorrect = false,
                            QuestionId = new Guid("3c933504-e478-4984-9044-365bd27ccb6c"),
                            Text = "Ausencia de comunicación entre servicios"
                        },
                        new
                        {
                            Id = new Guid("a4aee812-2a6e-4a17-83f5-4942c3db8f1b"),
                            IsCorrect = true,
                            QuestionId = new Guid("3c933504-e478-4984-9044-365bd27ccb6c"),
                            Text = "Despliegue independiente por servicio"
                        },
                        new
                        {
                            Id = new Guid("e01251eb-a282-4550-9fd6-4e4731840988"),
                            IsCorrect = false,
                            QuestionId = new Guid("3c933504-e478-4984-9044-365bd27ccb6c"),
                            Text = "Una única base de datos compartida obligatoria"
                        },
                        new
                        {
                            Id = new Guid("fadc3e62-c0f6-4222-a183-829af84327b4"),
                            IsCorrect = false,
                            QuestionId = new Guid("21e727f6-2da0-401a-9211-6ca24a85648f"),
                            Text = "Abierto/Cerrado"
                        },
                        new
                        {
                            Id = new Guid("e4b1ec49-581d-47a3-8539-793fd038e771"),
                            IsCorrect = true,
                            QuestionId = new Guid("21e727f6-2da0-401a-9211-6ca24a85648f"),
                            Text = "Responsabilidad única"
                        },
                        new
                        {
                            Id = new Guid("0c7c8a6e-68ec-4859-b8ab-122c3d2e0f3c"),
                            IsCorrect = false,
                            QuestionId = new Guid("21e727f6-2da0-401a-9211-6ca24a85648f"),
                            Text = "Sustitución de Liskov"
                        },
                        new
                        {
                            Id = new Guid("d8503a01-3339-46ae-95c6-5f713b0e84f0"),
                            IsCorrect = false,
                            QuestionId = new Guid("21e727f6-2da0-401a-9211-6ca24a85648f"),
                            Text = "Inversión de dependencias"
                        },
                        new
                        {
                            Id = new Guid("0551a798-9577-4fc9-81fd-0fdf6907720f"),
                            IsCorrect = false,
                            QuestionId = new Guid("93a07525-cd78-42dd-bead-420e1cf7db0e"),
                            Text = "Factory"
                        },
                        new
                        {
                            Id = new Guid("d8e13761-ad7c-4857-9728-cfee81cc129a"),
                            IsCorrect = false,
                            QuestionId = new Guid("93a07525-cd78-42dd-bead-420e1cf7db0e"),
                            Text = "Observer"
                        },
                        new
                        {
                            Id = new Guid("197fafb0-891c-404b-a5f8-4ce22e22f7d3"),
                            IsCorrect = true,
                            QuestionId = new Guid("93a07525-cd78-42dd-bead-420e1cf7db0e"),
                            Text = "Singleton"
                        },
                        new
                        {
                            Id = new Guid("3560622c-6851-43dd-962c-ce8c59d41d85"),
                            IsCorrect = false,
                            QuestionId = new Guid("93a07525-cd78-42dd-bead-420e1cf7db0e"),
                            Text = "Decorator"
                        },
                        new
                        {
                            Id = new Guid("65e31c46-cb67-4d38-9dc2-695322fc953a"),
                            IsCorrect = false,
                            QuestionId = new Guid("990bd4b0-5e85-497e-a19e-2d4ef3d1263e"),
                            Text = "Caché local"
                        },
                        new
                        {
                            Id = new Guid("fe6fd12a-ce84-4c4a-82ce-a66c9f5ab717"),
                            IsCorrect = false,
                            QuestionId = new Guid("990bd4b0-5e85-497e-a19e-2d4ef3d1263e"),
                            Text = "Compilador"
                        },
                        new
                        {
                            Id = new Guid("9825d3fd-0cf7-4148-bf91-4b5fe92a1d52"),
                            IsCorrect = false,
                            QuestionId = new Guid("990bd4b0-5e85-497e-a19e-2d4ef3d1263e"),
                            Text = "Contenedor de dependencias"
                        },
                        new
                        {
                            Id = new Guid("583d0f0b-40f5-4a1f-b199-f8b78d60a099"),
                            IsCorrect = true,
                            QuestionId = new Guid("990bd4b0-5e85-497e-a19e-2d4ef3d1263e"),
                            Text = "Balanceador de carga"
                        },
                        new
                        {
                            Id = new Guid("3fa01924-ac0c-4276-90ab-a6c3407aa943"),
                            IsCorrect = true,
                            QuestionId = new Guid("41905891-a86f-44f1-b8f4-3bdc12105fc0"),
                            Text = "REST"
                        },
                        new
                        {
                            Id = new Guid("4aef8f31-4732-4fd0-9205-47ae7c4c6d7e"),
                            IsCorrect = false,
                            QuestionId = new Guid("41905891-a86f-44f1-b8f4-3bdc12105fc0"),
                            Text = "SOAP"
                        },
                        new
                        {
                            Id = new Guid("b82290b2-ece9-4510-ab39-9043ecaa4e05"),
                            IsCorrect = false,
                            QuestionId = new Guid("41905891-a86f-44f1-b8f4-3bdc12105fc0"),
                            Text = "gRPC binario puro"
                        },
                        new
                        {
                            Id = new Guid("2246117f-ffef-47d2-87e7-6c6e95485867"),
                            IsCorrect = false,
                            QuestionId = new Guid("41905891-a86f-44f1-b8f4-3bdc12105fc0"),
                            Text = "FTP"
                        },
                        new
                        {
                            Id = new Guid("02e173bd-e815-412b-8e4a-c1a29ed15933"),
                            IsCorrect = false,
                            QuestionId = new Guid("7d196c04-6a14-4946-959a-17166e0ad1f2"),
                            Text = "CRUD"
                        },
                        new
                        {
                            Id = new Guid("d3334534-dc85-4d1e-a526-f6f8fb915895"),
                            IsCorrect = false,
                            QuestionId = new Guid("7d196c04-6a14-4946-959a-17166e0ad1f2"),
                            Text = "TDD"
                        },
                        new
                        {
                            Id = new Guid("493e677c-02e7-44ee-b46f-41326ec5bcce"),
                            IsCorrect = true,
                            QuestionId = new Guid("7d196c04-6a14-4946-959a-17166e0ad1f2"),
                            Text = "ETL"
                        },
                        new
                        {
                            Id = new Guid("3b60fd8b-7b44-46a4-89a4-6771d4ec1995"),
                            IsCorrect = false,
                            QuestionId = new Guid("7d196c04-6a14-4946-959a-17166e0ad1f2"),
                            Text = "CI/CD"
                        },
                        new
                        {
                            Id = new Guid("9b91d187-6b96-483b-a3b7-ce4a51bdf5fe"),
                            IsCorrect = false,
                            QuestionId = new Guid("5d34c73c-1f5a-4685-ad54-bee58fbf677d"),
                            Text = "Normalización por lotes"
                        },
                        new
                        {
                            Id = new Guid("206b1a69-23b1-424b-95a7-c744fa847946"),
                            IsCorrect = true,
                            QuestionId = new Guid("5d34c73c-1f5a-4685-ad54-bee58fbf677d"),
                            Text = "Retropropagación"
                        },
                        new
                        {
                            Id = new Guid("39ec0665-b326-4be1-b7fd-6d55fef959c1"),
                            IsCorrect = false,
                            QuestionId = new Guid("5d34c73c-1f5a-4685-ad54-bee58fbf677d"),
                            Text = "Poda de árboles"
                        },
                        new
                        {
                            Id = new Guid("4c8d96ab-3e97-4d49-bc59-a404d215ada1"),
                            IsCorrect = false,
                            QuestionId = new Guid("5d34c73c-1f5a-4685-ad54-bee58fbf677d"),
                            Text = "Validación cruzada"
                        },
                        new
                        {
                            Id = new Guid("d8a06579-66d7-434e-b37d-38037079f444"),
                            IsCorrect = false,
                            QuestionId = new Guid("b85875b3-e141-4392-9447-58d2f2efbdd9"),
                            Text = "Base de datos de grafos"
                        },
                        new
                        {
                            Id = new Guid("766fd5ca-8bf8-4ab0-9152-9979f44cc6af"),
                            IsCorrect = false,
                            QuestionId = new Guid("b85875b3-e141-4392-9447-58d2f2efbdd9"),
                            Text = "Base de datos documental"
                        },
                        new
                        {
                            Id = new Guid("7f43030c-1af6-453e-bb37-0944198860a7"),
                            IsCorrect = false,
                            QuestionId = new Guid("b85875b3-e141-4392-9447-58d2f2efbdd9"),
                            Text = "Base de datos clave-valor"
                        },
                        new
                        {
                            Id = new Guid("c3e6a42e-2860-47f9-8187-abf6f6d548e2"),
                            IsCorrect = true,
                            QuestionId = new Guid("b85875b3-e141-4392-9447-58d2f2efbdd9"),
                            Text = "Base de datos columnar"
                        },
                        new
                        {
                            Id = new Guid("d10505ae-96ab-4099-9a30-3a96021658a5"),
                            IsCorrect = false,
                            QuestionId = new Guid("a2e5ba2d-6dc1-47df-aeeb-e1540aa644ed"),
                            Text = "Perceptrón simple"
                        },
                        new
                        {
                            Id = new Guid("7165f901-b72f-432a-a266-9cf5f9c44e62"),
                            IsCorrect = true,
                            QuestionId = new Guid("a2e5ba2d-6dc1-47df-aeeb-e1540aa644ed"),
                            Text = "Transformer"
                        },
                        new
                        {
                            Id = new Guid("c62e8a06-f2c2-4ba6-bc4c-76367d2503a6"),
                            IsCorrect = false,
                            QuestionId = new Guid("a2e5ba2d-6dc1-47df-aeeb-e1540aa644ed"),
                            Text = "Red de Hopfield"
                        },
                        new
                        {
                            Id = new Guid("0f37d8d4-e79f-46d6-9dd1-3a1bb07c199a"),
                            IsCorrect = false,
                            QuestionId = new Guid("a2e5ba2d-6dc1-47df-aeeb-e1540aa644ed"),
                            Text = "Máquina de vectores de soporte"
                        },
                        new
                        {
                            Id = new Guid("ef215a79-7aad-4013-864e-bf764a007a9c"),
                            IsCorrect = true,
                            QuestionId = new Guid("4917bb8d-f18b-4afa-b437-4da489b75567"),
                            Text = "Apache Airflow"
                        },
                        new
                        {
                            Id = new Guid("d0f86c95-7cb3-4e86-a922-3f8fc67cc445"),
                            IsCorrect = false,
                            QuestionId = new Guid("4917bb8d-f18b-4afa-b437-4da489b75567"),
                            Text = "Apache Kafka"
                        },
                        new
                        {
                            Id = new Guid("e1532ac7-042e-4653-84d3-be7f8ea5302e"),
                            IsCorrect = false,
                            QuestionId = new Guid("4917bb8d-f18b-4afa-b437-4da489b75567"),
                            Text = "Redis"
                        },
                        new
                        {
                            Id = new Guid("3145ff07-0517-49a6-bb02-96e59b490d49"),
                            IsCorrect = false,
                            QuestionId = new Guid("4917bb8d-f18b-4afa-b437-4da489b75567"),
                            Text = "NGINX"
                        },
                        new
                        {
                            Id = new Guid("224fab6e-24cb-4902-a89a-bc02cf2dfe3d"),
                            IsCorrect = false,
                            QuestionId = new Guid("45080bdc-002e-40b3-9027-15e764ff5c63"),
                            Text = "Latencia"
                        },
                        new
                        {
                            Id = new Guid("7f768266-e394-4fbe-9c29-55e5c6ef418b"),
                            IsCorrect = false,
                            QuestionId = new Guid("45080bdc-002e-40b3-9027-15e764ff5c63"),
                            Text = "Cobertura de código"
                        },
                        new
                        {
                            Id = new Guid("f671855e-9d4b-4571-b6e8-e38ad8101aa1"),
                            IsCorrect = false,
                            QuestionId = new Guid("45080bdc-002e-40b3-9027-15e764ff5c63"),
                            Text = "Complejidad ciclomática"
                        },
                        new
                        {
                            Id = new Guid("d125b2ae-cf90-4051-9f27-c65084125f25"),
                            IsCorrect = true,
                            QuestionId = new Guid("45080bdc-002e-40b3-9027-15e764ff5c63"),
                            Text = "Precisión (Precision)"
                        });
                });

            modelBuilder.Entity("QuizGame.Domain.Questions.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "IsActive");

                    b.ToTable("Questions", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bca1ad0d-c8e0-48f7-a83e-39d71540c206"),
                            CategoryId = new Guid("59ef08e6-1514-4379-87a1-c1b802d616ba"),
                            IsActive = true,
                            Text = "¿Qué significa la sigla API?"
                        },
                        new
                        {
                            Id = new Guid("2a32cdc7-1c3a-4d84-b9e0-06ce7fca26ac"),
                            CategoryId = new Guid("59ef08e6-1514-4379-87a1-c1b802d616ba"),
                            IsActive = true,
                            Text = "¿Cuál de las siguientes opciones es un sistema de control de versiones?"
                        },
                        new
                        {
                            Id = new Guid("095aa9ae-8d60-46a1-bba6-78e9fa6c86e7"),
                            CategoryId = new Guid("59ef08e6-1514-4379-87a1-c1b802d616ba"),
                            IsActive = true,
                            Text = "¿Qué estructura de datos sigue el principio \"primero en entrar, primero en salir\" (FIFO)?"
                        },
                        new
                        {
                            Id = new Guid("7992d28c-4399-4180-a957-8755f76e1184"),
                            CategoryId = new Guid("59ef08e6-1514-4379-87a1-c1b802d616ba"),
                            IsActive = true,
                            Text = "¿Qué lenguaje se usa principalmente para dar estilo a las páginas web?"
                        },
                        new
                        {
                            Id = new Guid("427c79c8-d4b8-48c4-9308-b7eb1ddf140e"),
                            CategoryId = new Guid("59ef08e6-1514-4379-87a1-c1b802d616ba"),
                            IsActive = true,
                            Text = "¿Qué significa la sigla SQL?"
                        },
                        new
                        {
                            Id = new Guid("a4999ba8-15f3-4585-844a-0f0e1f17dcee"),
                            CategoryId = new Guid("59ef08e6-1514-4379-87a1-c1b802d616ba"),
                            IsActive = true,
                            Text = "¿Cuál de estas opciones es un tipo de dato primitivo en la mayoría de lenguajes de programación?"
                        },
                        new
                        {
                            Id = new Guid("3fa633a4-6979-45a9-a589-cf8c2754b6ec"),
                            CategoryId = new Guid("36cafaf0-b7cd-4556-9ac7-4b5b83f39118"),
                            IsActive = true,
                            Text = "¿Qué patrón arquitectónico separa una aplicación en Modelo, Vista y Controlador?"
                        },
                        new
                        {
                            Id = new Guid("3c933504-e478-4984-9044-365bd27ccb6c"),
                            CategoryId = new Guid("36cafaf0-b7cd-4556-9ac7-4b5b83f39118"),
                            IsActive = true,
                            Text = "¿Cuál de los siguientes es un principio de los sistemas orientados a microservicios?"
                        },
                        new
                        {
                            Id = new Guid("21e727f6-2da0-401a-9211-6ca24a85648f"),
                            CategoryId = new Guid("36cafaf0-b7cd-4556-9ac7-4b5b83f39118"),
                            IsActive = true,
                            Text = "¿Qué principio SOLID establece que una clase debe tener una única razón para cambiar?"
                        },
                        new
                        {
                            Id = new Guid("93a07525-cd78-42dd-bead-420e1cf7db0e"),
                            CategoryId = new Guid("36cafaf0-b7cd-4556-9ac7-4b5b83f39118"),
                            IsActive = true,
                            Text = "¿Qué patrón de diseño garantiza que una clase tenga una única instancia global?"
                        },
                        new
                        {
                            Id = new Guid("990bd4b0-5e85-497e-a19e-2d4ef3d1263e"),
                            CategoryId = new Guid("36cafaf0-b7cd-4556-9ac7-4b5b83f39118"),
                            IsActive = true,
                            Text = "¿Qué componente se utiliza típicamente para distribuir la carga entre varias instancias de un servicio?"
                        },
                        new
                        {
                            Id = new Guid("41905891-a86f-44f1-b8f4-3bdc12105fc0"),
                            CategoryId = new Guid("36cafaf0-b7cd-4556-9ac7-4b5b83f39118"),
                            IsActive = true,
                            Text = "¿Qué estilo arquitectónico expone recursos mediante URIs y verbos HTTP?"
                        },
                        new
                        {
                            Id = new Guid("7d196c04-6a14-4946-959a-17166e0ad1f2"),
                            CategoryId = new Guid("1ab48485-17e9-4eae-bcf6-113bbf0135c6"),
                            IsActive = true,
                            Text = "¿Qué proceso describe la extracción, transformación y carga de datos entre sistemas?"
                        },
                        new
                        {
                            Id = new Guid("5d34c73c-1f5a-4685-ad54-bee58fbf677d"),
                            CategoryId = new Guid("1ab48485-17e9-4eae-bcf6-113bbf0135c6"),
                            IsActive = true,
                            Text = "¿Qué técnica de aprendizaje automático ajusta los pesos de una red neuronal usando el gradiente del error?"
                        },
                        new
                        {
                            Id = new Guid("b85875b3-e141-4392-9447-58d2f2efbdd9"),
                            CategoryId = new Guid("1ab48485-17e9-4eae-bcf6-113bbf0135c6"),
                            IsActive = true,
                            Text = "¿Qué tipo de base de datos está optimizada para el almacenamiento y consulta analítica de grandes volúmenes de datos en columnas?"
                        },
                        new
                        {
                            Id = new Guid("a2e5ba2d-6dc1-47df-aeeb-e1540aa644ed"),
                            CategoryId = new Guid("1ab48485-17e9-4eae-bcf6-113bbf0135c6"),
                            IsActive = true,
                            Text = "¿Qué arquitectura de red neuronal se destaca por su uso del mecanismo de atención y es la base de los modelos de lenguaje modernos?"
                        },
                        new
                        {
                            Id = new Guid("4917bb8d-f18b-4afa-b437-4da489b75567"),
                            CategoryId = new Guid("1ab48485-17e9-4eae-bcf6-113bbf0135c6"),
                            IsActive = true,
                            Text = "¿Qué herramienta se utiliza comúnmente para orquestar flujos de trabajo de datos (pipelines) por lotes?"
                        },
                        new
                        {
                            Id = new Guid("45080bdc-002e-40b3-9027-15e764ff5c63"),
                            CategoryId = new Guid("1ab48485-17e9-4eae-bcf6-113bbf0135c6"),
                            IsActive = true,
                            Text = "¿Qué métrica evalúa la proporción de verdaderos positivos sobre el total de positivos predichos por un modelo de clasificación?"
                        });
                });

            modelBuilder.Entity("QuizGame.Infrastructure.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponsePayload")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("ExpiresOnUtc")
                        .HasDatabaseName("IX_IdempotencyRecords_ExpiresOnUtc");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("UQ_IdempotencyRecords_RequestId");

                    b.ToTable("IdempotencyRecords", "dbo");
                });

            modelBuilder.Entity("QuizGame.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc")
                        .HasDatabaseName("IX_OutboxMessages_Pending")
                        .HasFilter("[ProcessedOnUtc] IS NULL");

                    b.ToTable("OutboxMessages", "dbo");
                });

            modelBuilder.Entity("QuizGame.Domain.Games.Game", b =>
                {
                    b.OwnsOne("QuizGame.Domain.Games.GameSettings", "Settings", b1 =>
                        {
                            b1.Property<Guid>("GameId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<TimeSpan>("QuestionTimeLimit")
                                .HasColumnType("time")
                                .HasColumnName("QuestionTimeLimit");

                            b1.Property<int>("TotalRounds")
                                .HasColumnType("int")
                                .HasColumnName("TotalRounds");

                            b1.HasKey("GameId");

                            b1.ToTable("Games", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("GameId");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("QuizGame.Domain.Games.Round", b =>
                {
                    b.HasOne("QuizGame.Domain.Games.Game", null)
                        .WithMany("Rounds")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizGame.Domain.Questions.Answer", b =>
                {
                    b.HasOne("QuizGame.Domain.Questions.Question", null)
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizGame.Domain.Questions.Question", b =>
                {
                    b.HasOne("QuizGame.Domain.Categories.Category", null)
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizGame.Domain.Categories.Category", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizGame.Domain.Games.Game", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("QuizGame.Domain.Questions.Question", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
